## 1. 벡터, 행렬 그리고 텐서 (Vector, Matrix and Tensor)

* 스칼라: 차원이 없는 값
* 벡터: 1차원으로 구성된 값 (1d-tensor)
* 행렬(Matrix): 2차원으로 구성된 값 (2d-tensor)
* 텐서(Tensor): 스칼라, 벡터, 행렬을 포함하는 일반적인 다차원 배열 구조

In [1]:
from IPython.display import Image
Image(url='https://raw.githubusercontent.com/Hyelim-Shin/AIdev/Images/tensor.png', width=500)

#### Example

In [8]:
import numpy as np
import pandas as pd

data = [['나는', '사과를', '좋아해'], ['나는', '바나나를', '좋아해'], ['나는', '사과를', '싫어해'], ['나는', '바나나를', '싫어해']]
word2vec = {'나는':[0.1, 0.2, 0.9], '사과를':[0.3, 0.5, 0.1], '바나나를':[0.3, 0.5, 0.2], '좋아해':[0.7, 0.6, 0.5], '싫어해':[0.5, 0.6, 0.7]}

vec_data = [[word2vec[word] for word in sentence] for sentence in data]

tensor = np.array(vec_data, dtype=np.float32)
tensor


array([[[0.1, 0.2, 0.9],
        [0.3, 0.5, 0.1],
        [0.7, 0.6, 0.5]],

       [[0.1, 0.2, 0.9],
        [0.3, 0.5, 0.2],
        [0.7, 0.6, 0.5]],

       [[0.1, 0.2, 0.9],
        [0.3, 0.5, 0.1],
        [0.5, 0.6, 0.7]],

       [[0.1, 0.2, 0.9],
        [0.3, 0.5, 0.2],
        [0.5, 0.6, 0.7]]], dtype=float32)

In [12]:
# (batch size, 문장 길이, 단어 벡터의 차원)
tensor.shape

(4, 3, 3)

In [ ]:
Image(url='https://raw.githubusercontent.com/Hyelim-Shin/AIdev/Images/NLP-3D-tensor.png', width=500)

## 2. 파이토치

### 1) 파이토치란?
* 2016년에 공개된 딥러닝 프레임워크
* 루아(Lua) 언어로 개발되었던 토치(Torch)를 FAIR(Facebook AI Research)에서 파이썬 버전으로 내놓은 것
* 파이썬의 넘파이(NumPy) 라이브러리처럼 과학연산을 위한 라이브러리로 공개되었지만 이후 발전을 거듭하면서 딥러닝 프레임워크로 발전
* GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크

#### 파이토치 텐서 선언하기

In [ ]:
import torch

In [18]:
# 1차원 텐서
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print(tensor_1d)

tensor([1, 2, 3, 4, 5])


In [20]:
print(tensor_1d.dim())  # rank. 즉, 차원
print(tensor_1d.shape)  # shape
print(tensor_1d.size()) # shape

1
torch.Size([5])
torch.Size([5])


In [ ]:
print(tensor_1d[0], tensor_1d[1], tensor_1d[-1])  # 인덱스로 접근
print(tensor_1d[2:5], tensor_1d[4:-1])    # 슬라이싱
print(tensor_1d[:2], tensor_1d[3:])       # 슬라이싱

tensor(1) tensor(2) tensor(5)
tensor([3, 4, 5]) tensor([], dtype=torch.int64)
tensor([1, 2]) tensor([4, 5])


In [22]:
tensor_2d = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(tensor_2d)


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [23]:
print(tensor_2d.dim())  # rank. 즉, 차원
print(tensor_2d.size()) # shape

2
torch.Size([4, 3])


In [24]:
print(tensor_2d[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])




### 2) 파이토치 패키지의 기본 구성

1. ```torch```
    * 메인 네임스페이스. 텐서 등의 다양한 수학 함수가 포함되어져 있으며 Numpy와 유사한 구조
2. ```torch.autograd```
    * 자동 미분을 위한 함수들이 포함
3. ```torch.nn```
    * 신경망을 구축하기 위한 다양한 데이터 구조나 레이어 등이 정의되어 있음
4. ```torch.optim```
    * 확률적 경사 하강법 (Stochastic Gradient Descent, SGD)를 중심으로 한 파라미터 최적화 알고리즘이 구현되어 있음.
5. ```torch.utils.data```
    * SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함.
6. ```torch.onnx```
    * ONNX(Open Neural Network Exchange)의 포맷으로 모델을 익스포트(export)할 때 사용. ONNX는 서로 다른 딥 러닝 프레임워크 간에 모델을 공유할 때 사용하는 포맷.


### 3) 계산 그래프
* 파이토치는 유향 비순환 그래프(Directed Acyclic Graph, DAG)를 기반으로 계산을 수행
    - 노드(node): 변수(텐서 등)를 의미
    - 엣지(edge): 연산(곱하기, 더하기 등)을 의미

<center>

$z=2\times(a-b)+c$

</center>


In [17]:
# 파이토치 계산 그래프
Image(url='https://raw.githubusercontent.com/rickiepark/ml-with-pytorch/main/ch13/figures/13_01.png', width=400)

#### 파이토치로 그래프 만들기

In [15]:
import torch

In [ ]:
def compute_z(a, b, c):
    r1 = torch.sub(a, b)
    r2 = torch.mul(r1, 2)
    z = torch.add(r2, c)
    return z

print('스칼라 입력:', compute_z(torch.tensor(1), torch.tensor(2), torch.tensor(3)))
print('랭크 1 입력:', compute_z(torch.tensor([1]), torch.tensor([2]), torch.tensor([3])))
print('랭크 2 입력:', compute_z(torch.tensor([[1]]), torch.tensor([[2]]), torch.tensor([[3]])))

스칼라 입력: tensor(1)
랭크 1 입력: tensor([1])
랭크 2 입력: tensor([[1]])


### 4) 자주 사용되는 파이토치 기능들

#### (1) 행렬 곱셈과 곱셈 (Matrix Multiplication and Multiplication)

In [25]:
## 행렬 곱
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1


Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [26]:
## element-wise 곱
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


**브로드캐스팅(Broadcasting)**
* 크기가 다른 행렬 또는 텐서에 대해서 자동으로 크기를 맞춰 연산을 수행하는 기능

In [27]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)


tensor([[4., 5.]])


In [28]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)


tensor([[4., 5.],
        [5., 6.]])


#### (2) 평균(Mean)

In [31]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())


tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [ ]:
print(t.mean(dim=0)) # 행을 제거
print(t.mean(dim=1)) # 열을 제거

tensor([2., 3.])
tensor([1.5000, 3.5000])


In [34]:
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


#### (3) 덧셈 (Sum)

In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거


tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#### (4) 최대(Max)와 아그맥스(ArgMax)

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max()) # Returns one value: max

tensor(4.)


In [38]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [39]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])


Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [40]:
print(t.max(dim=1))
print(t.max(dim=-1))


torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


#### (5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!

넘파이에서의 ```reshape```와 같은 역할. 텐서의 크기 변경

In [42]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)  # (2, 2, 3)

torch.Size([2, 2, 3])


In [43]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)


tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


* view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 함
* 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추

In [44]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


#### (6) 스퀴즈(Squeeze)와 언스퀴즈(Unsqueeze)

* 스퀴즈(Squeeze): 1인 차원을 제거
* 언스퀴즈(Unsqueeze): 특정 위치에 1인 차원을 추가

In [45]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
## Squeeze
print(ft.squeeze())
print(ft.squeeze().shape)


tensor([0., 1., 2.])
torch.Size([3])


In [47]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [ ]:
## Unsqueeze
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [50]:
## View와 Unsqueeze가 같은 결과
print(ft.view(1, -1))
print(ft.view(1, -1).shape)


tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [51]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [52]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


#### (7) 연결하기(concatenate)

In [53]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])


In [ ]:
## cat 함수로 텐서 연결하기
print(torch.cat([x, y]))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [54]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [55]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [58]:
## stack 함수로 텐서 연결하기
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [59]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [60]:
Image(url='https://raw.githubusercontent.com/Hyelim-Shin/AIdev/Images/stack.png', width=200)

In [61]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [62]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### (8) ones_like와 zeros_like

In [63]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [64]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [65]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])
